#!/bin/bash

argOne=1
argTwo=2
argThree=3

javac src/regagent/*.java
javac src/proxy/*.java
javac -cp .:src:src/regagent:src/proxy src/*.java
java -cp .:src:src/regagent:src/proxy src.TorMain ${!argOne} ${!argTwo} ${!argThree}
